In [ ]:
# numpy library for equations deal with numbers and arrays and it can use for 
#algebra and liner 

In [ ]:
#if u dont have it type pip install numpy

In [ ]:
#to open all library we use import ### from ###

In [ ]:
#down here we import numpy as np to shortcut the name (numpy)
#and arange is mean 

In [4]:
 help(range) #help(function) to know functions help

Help on class range in module builtins:

class range(object)
 |  range(stop) -> range object
 |  range(start, stop[, step]) -> range object
 |  
 |  Return an object that produces a sequence of integers from start (inclusive)
 |  to stop (exclusive) by step.  range(i, j) produces i, i+1, i+2, ..., j-1.
 |  start defaults to 0, and stop is omitted!  range(4) produces 0, 1, 2, 3.
 |  These are exactly the valid indices for a list of 4 elements.
 |  When step is given, it specifies the increment (or decrement).
 |  
 |  Methods defined here:
 |  
 |  __bool__(self, /)
 |      self != 0
 |  
 |  __contains__(self, key, /)
 |      Return key in self.
 |  
 |  __eq__(self, value, /)
 |      Return self==value.
 |  
 |  __ge__(self, value, /)
 |      Return self>=value.
 |  
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |  
 |  __getitem__(self, key, /)
 |      Return self[key].
 |  
 |  __gt__(self, value, /)
 |      Return self>value.
 |  
 |  __hash__(self, /)
 |

In [5]:
# reshape do re oreder array 
import numpy as np
a = np.arange(15)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [1]:
import numpy as np
a = np.arange(15).reshape(3, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [2]:
import numpy as np 

print(np.array([8, 4, 6, 0, 2]))

[8 4 6 0 2]


In [6]:
print('create a 2-d array by passing a list of lists into array().')
A = np.array( [ [1, 2, 3],[4, 5,6], [7, 8, 9] ] )
print(A)

# here to access 2d first bracket for the arrays and second 
#array for the element iside the array 
#so here a[0.1] mean array 0 and 1
#and a(1.2)mean array 0 elemnt 1 and elemnt2 in array 1
print('Access elemnts of the array with brackets.')
print(A[0, 1], A[1, 2])

print('the elemnts of a 2-d array are 1d arrays')
print(A[0])

create a 2-d array by passing a list of lists into array().
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Access elemnts of the array with brackets.
2 6
the elemnts of a 2-d array are 1d arrays
[1 2 3]


## exercise 1.1

In [ ]:
    a= np.arry([],[])
    b=np.array([],[],[])
    
dot_Array(a, b)  

def dot_Array(a, b):
    z=np.dot(a, b)
    
    print(z)
    #return or print

## exrcise 1.2

In [ ]:
#np.ndarray -> go to help(ndarray) and give example 

## 1.2 basic array operations

In [8]:
# here the operations on arrays 
#operations on arrays are differnt that usual operations
print('Addition concatenates lists together')
print([1, 2, 3]+[4, 5, 6])

print('mutliplication concatenates a list with itself a given number of times')
print([1, 2, 3] * 4)

Addition concatenates lists together
[1, 2, 3, 4, 5, 6]
mutliplication concatenates a list with itself a given number of times
[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]


## exercise 1.3

In [10]:
x=np.array([3, -4, 1])
y=np.array([5, 2, 3])
z = x + 10


print(z)

[13  6 11]


## array attributes

In [39]:

# from 0 to 50 add 10
x = np.arange(0, 50, 10)
index = np.array([3, 1, 4])
print(x)
print(x[index])

mask = np.array([True, False, False, True, False])
print(x[mask])

[ 0 10 20 30 40]
[30 10 40]
[ 0 30]


In [11]:
y= np.arange(10, 20, 2)
print(y)
mask = y > 15
print(mask)
print(y[mask])

y[mask] = 100
print(y)

[10 12 14 16 18]
[False False False  True  True]
[16 18]
[ 10  12  14 100 100]


In [ ]:
#sklearn library 

In [11]:
from sklearn import datasets

iris = datasets.load_iris()
print(iris.filename)

C:\Users\2\anaconda3\lib\site-packages\sklearn\datasets\data\iris.csv


In [ ]:
#this library give data set default

In [21]:
import numpy as np 
iris_data = np.genfromtxt('C:\\Users\\2\\anaconda3\\lib\\site-packages\\sklearn\\datasets\\data\\iris.csv', delimiter=",", skip_header=1)
print(iris_data)

array([[1.5e+02, 4.0e+00,     nan,     nan,     nan],
       [5.1e+00, 3.5e+00, 1.4e+00, 2.0e-01, 0.0e+00],
       [4.9e+00, 3.0e+00, 1.4e+00, 2.0e-01, 0.0e+00],
       [4.7e+00, 3.2e+00, 1.3e+00, 2.0e-01, 0.0e+00],
       [4.6e+00, 3.1e+00, 1.5e+00, 2.0e-01, 0.0e+00],
       [5.0e+00, 3.6e+00, 1.4e+00, 2.0e-01, 0.0e+00],
       [5.4e+00, 3.9e+00, 1.7e+00, 4.0e-01, 0.0e+00],
       [4.6e+00, 3.4e+00, 1.4e+00, 3.0e-01, 0.0e+00],
       [5.0e+00, 3.4e+00, 1.5e+00, 2.0e-01, 0.0e+00],
       [4.4e+00, 2.9e+00, 1.4e+00, 2.0e-01, 0.0e+00],
       [4.9e+00, 3.1e+00, 1.5e+00, 1.0e-01, 0.0e+00],
       [5.4e+00, 3.7e+00, 1.5e+00, 2.0e-01, 0.0e+00],
       [4.8e+00, 3.4e+00, 1.6e+00, 2.0e-01, 0.0e+00],
       [4.8e+00, 3.0e+00, 1.4e+00, 1.0e-01, 0.0e+00],
       [4.3e+00, 3.0e+00, 1.1e+00, 1.0e-01, 0.0e+00],
       [5.8e+00, 4.0e+00, 1.2e+00, 2.0e-01, 0.0e+00],
       [5.7e+00, 4.4e+00, 1.5e+00, 4.0e-01, 0.0e+00],
       [5.4e+00, 3.9e+00, 1.3e+00, 4.0e-01, 0.0e+00],
       [5.1e+00, 3.5e+00, 1.

In [19]:
#column names
iris.feature_names


['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [19]:
import numpy as np 
iris_data = np.genfromtxt('C:\\Users\\2\\anaconda3\\lib\\site-packages\\sklearn\\datasets\\data\\iris.csv', delimiter=",", skip_header=1)

print("mean of {} is {}".format(iris.feature_names[0], iris_data[:,0].mean()))


mean of sepal length (cm) is 5.843333333333334


In [35]:

print(iris_data[3, : ].mean())

1.8800000000000001


In [36]:
print(iris_data[3, : ].max())

4.7


In [38]:
print(iris_data[3, : ].min())

0.0
